<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8" />
		<title>Exercice blog MVC</title>
	</head>
	<body>
    <header>
        <h1>Mon blog</h1>
        <nav>
            <ul>
                <li>
                    <a href="index.php">Accueil</a>
            </li>
                <li>
                    <a href="index.php?route=categories">Catégories</a>
                </li>
                <li>
                    <a href="index.php?route=category">Category</a>
                </li>
                <li>
                    <a href="index.php?route=post">Post</a>
            </li>
            </ul>
        </nav>
    </header>
    <main>
        <?php 
        require "templates/$template.phtml";
        ?>
    </main>
    <footer>
        <p> Mon blog</p>
    </footer>
</body>
</html>